/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import component.ProgressBar;
import component.UserSession;
import config.ConnectDB;
import java.awt.GridBagConstraints;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import java.time.format.TextStyle;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author adam x rezaa
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        CbMonthInit();
        CbYearInit();
        TbLoad();
        ProgressBarInit();
        UserSession.setPanelOpened("Dashboard");
    }
    
    Statement st;
    Connection con = ConnectDB.getConnection();
    ResultSet rs;
    DefaultTableModel model;
    SimpleDateFormat df;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(800, 500));
        setName("Dashboard"); // NOI18N
        setLayout(new java.awt.BorderLayout(5, 5));

        jScrollPane1.setBorder(null);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(150, 450));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 450));

        jPanel3.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        jPanel3.setPreferredSize(new java.awt.Dimension(180, 500));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(javax.swing.UIManager.getDefaults().getColor("TextArea.background"));
        jPanel4.setPreferredSize(new java.awt.Dimension(182, 80));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Kemajuan Pembayaran");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel4.add(jLabel2, gridBagConstraints);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel4.add(jComboBox1, gridBagConstraints);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel4.add(jComboBox2, gridBagConstraints);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setPreferredSize(new java.awt.Dimension(190, 450));
        jPanel5.setLayout(new java.awt.GridBagLayout());
        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel3);

        add(jScrollPane1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("TextArea.background"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        try {
            ProgressBarInit();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        try {
            ProgressBarInit();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
    private void CbMonthInit() {
        // Create array of months for combo box
        Month[] months = Month.values();
        String[] monthStrings = new String[months.length];
        for (int i = 0; i < months.length; i++) {
            monthStrings[i] = months[i].getDisplayName(TextStyle.FULL_STANDALONE, new Locale("id", "ID"));
        }

        // Create default combo box model and set it to the combo box
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(monthStrings);
        jComboBox1.setModel(model);

        // Select current month by default
        Month thisMonth = LocalDate.now().getMonth();
        jComboBox1.setSelectedItem(thisMonth.getDisplayName(TextStyle.FULL_STANDALONE, new Locale("id", "ID")));
    }
    private void CbYearInit() {
        // Create array of years for combo box
        int currentYear = LocalDate.now().getYear();
        Integer[] yearNumbers = new Integer[201];
        for (int i = 0; i < yearNumbers.length; i++) {
            yearNumbers[i] = currentYear - 100 + i;
        }

        // Create default combo box model and set it to the combo box
        DefaultComboBoxModel modelYear = new DefaultComboBoxModel<>(yearNumbers);
        jComboBox2.setModel(modelYear);

        // Select current year by default
        jComboBox2.setSelectedItem(currentYear);
    }
    
    private void TbLoad() {
        String[] judul = {"ID Transaksi", "Siswa", "Tanggal", "Pembayaran", "Jumlah", "Petugas"};
        model = new DefaultTableModel(judul,0) {
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        jTable1.setModel(model);
        df = new SimpleDateFormat("dd-MM-yyyy");
        String sql = "SELECT payment.id_transaksi, student.nama AS nama_siswa, payment.tanggal_bayar, payment.bulan, payment.tahun, payment.jumlah_bayar, user.nama AS nama_petugas\n" +
                "FROM payment\n" +
                "JOIN student ON payment.nis = student.nis\n" +
                "JOIN user ON payment.id_petugas = user.id_petugas\n" +
                "ORDER BY payment.tanggal_bayar DESC;";
        try {
            rs = con.createStatement().executeQuery(sql);
            
            while(rs.next()) {
                String idTransaction = rs.getString("id_transaksi");
                String studentName = rs.getString("nama_siswa");
                String date = df.format(rs.getDate("tanggal_bayar"));
                String month = rs.getString("bulan") + " " + rs.getString("tahun");
                String fee = rs.getString("jumlah_bayar");
                String officerName = rs.getString("nama_petugas");

                String[] data = {idTransaction, studentName, date, month, fee, officerName};
                model.addRow(data);
           }
        }catch(Exception e) {
           System.out.println(e);
        }
    }
    private void ProgressBarInit() {
        jPanel5.removeAll();
        jPanel5.revalidate();
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.NORTH;
        
        String sql = "SELECT class.nama_kelas, COUNT(student.nis) AS jumlah_siswa, COUNT(payment.id_transaksi) AS jumlah_pembayaran\n" +
                "FROM class\n" +
                "LEFT JOIN student ON class.id_kelas = student.id_kelas\n" +
                "LEFT JOIN payment ON student.nis = payment.nis AND payment.bulan = '"+ jComboBox1.getSelectedItem().toString() +"' AND tahun = '"+ jComboBox2.getSelectedItem().toString() +"'\n" +
                "GROUP BY class.nama_kelas;";
        try {
            rs = con.createStatement().executeQuery(sql);
            
            while(rs.next()) {
                String kelas = rs.getString("nama_kelas");
                int jumlah = Integer.parseInt(rs.getString("jumlah_siswa"));
                int bayar = Integer.parseInt(rs.getString("jumlah_pembayaran"));
               
                jPanel5.add(new ProgressBar(kelas, jumlah, bayar), gbc);
                gbc.gridy++;
           }
        }catch(Exception e) {
           System.out.println(e);
        }
    }
}
