/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import component.UserSession;
import config.ConnectDB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adam x rezaa
 */
public class LoginSiswa extends javax.swing.JFrame {
    Statement st;
    Connection con = ConnectDB.getConnection();
    ResultSet rs;
    SimpleDateFormat df;
    DefaultTableModel model;
    
    private String password;

    /**
     * Creates new form LoginSiswa
     */
    public LoginSiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnGlobal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtID_Pn1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        PnGlobal.setBackground(new java.awt.Color(255, 255, 255));
        PnGlobal.setMinimumSize(new java.awt.Dimension(400, 300));
        PnGlobal.setPreferredSize(new java.awt.Dimension(400, 300));
        PnGlobal.setLayout(new java.awt.GridBagLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/RFID.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        PnGlobal.add(jLabel3, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(8, 4, 188));
        jLabel2.setText("TAP YOUR ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.ipady = 4;
        PnGlobal.add(jLabel2, gridBagConstraints);

        TxtID_Pn1.setMinimumSize(new java.awt.Dimension(100, 26));
        TxtID_Pn1.setPreferredSize(new java.awt.Dimension(100, 26));
        TxtID_Pn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtID_Pn1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        PnGlobal.add(TxtID_Pn1, gridBagConstraints);

        getContentPane().add(PnGlobal, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtID_Pn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtID_Pn1ActionPerformed
        // TODO add your handling code here:
        String rfid = TxtID_Pn1.getText();

        try {
            String sql = "SELECT * FROM student WHERE rfid = '"+ rfid +"';";
            System.out.println(sql);
            Statement st = con.createStatement();
            rs = st.executeQuery(sql);

            if (rs.next()) {
                String id = rs.getString("nis");
                String stName = rs.getString("nama");

                UserSession.setId(id);
                UserSession.setName(stName);
                UserSession.setLevel("Siswa");
                
                JOptionPane.showMessageDialog(null, "Selamat datang, " + UserSession.getName() + "!", "Login Berhasil", JOptionPane.DEFAULT_OPTION);

                Main main = new Main();
                main.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Kartu tidak dikenali!");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        TxtID_Pn1.setText("");
    }//GEN-LAST:event_TxtID_Pn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnGlobal;
    private javax.swing.JTextField TxtID_Pn1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
