/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import component.UserSession;
import panel.*;

/**
 *
 * @author adam x rezaa
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setTitle("MySpp");
        initLevel(UserSession.getLevel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnMain = new javax.swing.JPanel();
        gradientPanel1 = new component.GradientPanel();
        PnLoggedInfo = new javax.swing.JPanel();
        LbLoggedName = new javax.swing.JLabel();
        LbLoggedLevel = new javax.swing.JLabel();
        LbTitle = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mn1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        PnMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        PnMain.setMinimumSize(new java.awt.Dimension(800, 500));
        PnMain.setPreferredSize(new java.awt.Dimension(800, 500));
        PnMain.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PnMain, java.awt.BorderLayout.CENTER);

        gradientPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        gradientPanel1.setkEndColor(new java.awt.Color(0, 23, 228));
        gradientPanel1.setkStartColor(new java.awt.Color(55, 147, 255));
        gradientPanel1.setLayout(new java.awt.BorderLayout());

        PnLoggedInfo.setOpaque(false);
        PnLoggedInfo.setLayout(new java.awt.GridBagLayout());

        LbLoggedName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        LbLoggedName.setForeground(new java.awt.Color(255, 255, 255));
        LbLoggedName.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PnLoggedInfo.add(LbLoggedName, gridBagConstraints);

        LbLoggedLevel.setForeground(new java.awt.Color(255, 255, 255));
        LbLoggedLevel.setText("Level");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PnLoggedInfo.add(LbLoggedLevel, gridBagConstraints);

        gradientPanel1.add(PnLoggedInfo, java.awt.BorderLayout.LINE_END);

        LbTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LbTitle.setForeground(new java.awt.Color(255, 255, 255));
        LbTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LbTitle.setText("MyApp");
        gradientPanel1.add(LbTitle, java.awt.BorderLayout.CENTER);

        getContentPane().add(gradientPanel1, java.awt.BorderLayout.PAGE_START);

        Mn1.setText("Menu");
        Mn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setText("Dashboard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Mn1.add(jMenuItem1);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem7.setText("Pembayaran");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        Mn1.add(jMenuItem7);

        jMenu1.setText("Data Center");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem2.setText("Siswa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem3.setText("Kelas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem4.setText("SPP");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem5.setText("Kategori");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem9.setText("Petugas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        Mn1.add(jMenu1);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem6.setText("Laporan");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        Mn1.add(jMenuItem6);
        Mn1.add(jSeparator1);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem8.setText("Logout");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        Mn1.add(jMenuItem8);

        jMenuBar1.add(Mn1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        PnMain.removeAll();
        PnMain.add(new Dashboard());
        LbTitle.setText(UserSession.getPanelOpened());
        PnMain.revalidate();
        PnMain.repaint();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        PnMain.removeAll();
        PnMain.add(new Payment());
        LbTitle.setText(UserSession.getPanelOpened());
        PnMain.revalidate();
        PnMain.repaint();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        PnMain.removeAll();
        PnMain.add(new MasterData(0));
        LbTitle.setText(UserSession.getPanelOpened());
        PnMain.revalidate();
        PnMain.repaint();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        PnMain.removeAll();
        PnMain.add(new MasterData(1));
        LbTitle.setText(UserSession.getPanelOpened());
        PnMain.revalidate();
        PnMain.repaint();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        PnMain.removeAll();
        PnMain.add(new MasterData(2));
        LbTitle.setText(UserSession.getPanelOpened());
        PnMain.revalidate();
        PnMain.repaint();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        PnMain.removeAll();
        PnMain.add(new MasterData(3));
        LbTitle.setText(UserSession.getPanelOpened());
        PnMain.revalidate();
        PnMain.repaint();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        PnMain.removeAll();
        PnMain.add(new MasterReport());
        LbTitle.setText(UserSession.getPanelOpened());
        PnMain.revalidate();
        PnMain.repaint();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        if (UserSession.getLevel().equals("Common User")) {
            dispose();
            new LoginSiswa().setVisible(true);
        } else {
            dispose();
            new Login().setVisible(true);
        }
        
        UserSession.setId("");
        UserSession.setLevel("");
        UserSession.setLevelName("");
        UserSession.setName("");
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        PnMain.removeAll();
        PnMain.add(new MasterData(4));
        LbTitle.setText(UserSession.getPanelOpened());
        PnMain.revalidate();
        PnMain.repaint();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbLoggedLevel;
    private javax.swing.JLabel LbLoggedName;
    private javax.swing.JLabel LbTitle;
    private javax.swing.JMenu Mn1;
    private javax.swing.JPanel PnLoggedInfo;
    private javax.swing.JPanel PnMain;
    private component.GradientPanel gradientPanel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
    
    private void init() {
        LbLoggedName.setText(UserSession.getName());
        LbLoggedLevel.setText(UserSession.getLevel());
        
        PnMain.removeAll();
        PnMain.add(new Dashboard());
        LbTitle.setText(UserSession.getPanelOpened());
        PnMain.revalidate();
        PnMain.repaint();
    }
    
    private void initLevel(String level) {
        switch (level) {
            case "Admin":
                init();
                break;
            case "Petugas":
                init();
                jMenu1.setVisible(false);
                break;
            case "Siswa":
                LbLoggedName.setText(UserSession.getName());
                LbLoggedLevel.setText(UserSession.getLevel());
                
                jMenu1.setVisible(false);
                jMenuItem1.setVisible(false);
                jMenuItem6.setVisible(false);
                jMenuItem7.setVisible(false);
                jSeparator1.setVisible(false);

                PnMain.removeAll();
                PnMain.add(new StudentView());
                LbTitle.setText(UserSession.getPanelOpened());
                PnMain.revalidate();
                PnMain.repaint();
                break;
            default:
                throw new AssertionError();
        }
    }
}
